name: ci

on: [push]

jobs:
  build_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm i -g yarn
      - run: yarn set version berry
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ./.yarn
          key: ${{ runner.os }}-yarn2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-
      - run: yarn install --immutable
        env:
          CI: true
      - run: yarn build
        env:
          CI: true
      - run: yarn lint
        env:
          CI: true
      - run: yarn test --ci --coverage --maxWorkers=2
        env:
          CI: true
  build_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile', 'setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: setup pipenv
        run: |
          python -m pip install pipenv
          pipenv install --dev
      - name: pytest
        shell: pipenv run bash {0}
        run: pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: Lint
        shell: pipenv run bash {0}
        run: npm run lint:p

      - name: Build Notebooks
        shell: pipenv run bash {0}
        run: jupyter nbconvert examples/*.ipynb --to html

      - name: Create Docu
        shell: pipenv run bash {0}
        run: npm run docs:p

      - run: |
          mkdir -p public/integrations/jupyter
          mv examples/*.html public/integrations/jupyter/
          mv public/integrations/jupyter/introduction.html public/integrations/jupyter/index.html

          mkdir -p public/api/jupyter
          mv docs/build/_static public/api/jupyter/static
          mv docs/build/*.js public/api/jupyter/
          mv docs/build/*.html public/api/jupyter/
          find . -type f -name "*.html" -print0 | xargs -0 sed -i 's/"_/"/g'

      - name: Deploy
        if: github.ref == 'refs/heads/develop'
        # move to next directory
        run: |
          mv public public2
          mkdir -p public
          mv public2 public/next

      - name: Deploy
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop') && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: upsetjs/upsetjs.github.io
          publish_branch: master
          publish_dir: ./public
          enable_jekyll: true
          keep_files: true
